name: Backpocket Environment Prep
description: Carlos personal CML project for preparing environments
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2022-03-29"

environment_variables:
  DATALAKE_ATLAS_ENDPOINT:
    description: >-
      URL can be found in CDP Management Console > Environments > Environment > Data Lake > Endpoints > Atlas.
      It looks like: https://{dl}-gateway.{env_name}.a465-9q4k.cloudera.site/{dl}/cdp-proxy-api/atlas/api/atlas/

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: create_job
    name: Install dependencies
    entity_label: install_dependencies
    script: scripts/install_dependencies.py
    arguments: None
    cpu: 1
    memory: 4
    short_summary: Create job to install project dependencies.
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: install_dependencies
    short_summary: Running install dependencies job.
    long_summary: >-
      Running the job to install dependencies.  Note that this requires at least 2GB of memory

  - type: run_session
    name: Catalogue open data
    script: code/load_open_data_catalogues.py
    short_summary: Create Atlas entities for open data catalogues of Toronto, Ontario, and Canada
    cpu: 2
    memory: 4
