name: Backpocket Environment Prep
description: Carlos personal CML project for preparing environments
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2022-03-29"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: create_job
    name: Install dependencies
    entity_label: install_deps
    script: scripts/install_dependencies.py
    arguments: None
    cpu: 2
    memory: 4
    short_summary: Create job to install project dependencies.
    environment:
      TASK_TYPE: CREATE/RUN_JOB
